name: Frontend CI Pipeline
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: recuperer le code
        uses: actions/checkout@v4

      - name: se connecter a docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: builder l'image docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }} .

      - name: pousser l'image docker
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }}

  deploy-gitops:
    runs-on: ubuntu-latest
    needs: build # Attendre que l'image soit sur Docker Hub
    steps:
      - name: Mise à jour du Repo GitOps
        run: |
          # 1. Configuration de l'identité Git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # 2. Clonage du repo GitOps (utilisez votre URL de repo K8s)
          # On utilise le GITOPS_TOKEN que vous avez configuré
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/achraf-77733/travelo_k8s.git gitops-repo

          cd gitops-repo

          # 3. Mise à jour du tag de l'image avec SED
          # Cette commande cherche l'image 'travelo_frontend' et remplace tout ce qui suit le ':' par le nouveau tag
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }}|g" frontend_deployment.yml
          # 4. Commit et Push
          git add .
          git commit -m "Update frontend image to ${{ github.ref_name }} [skip ci]"
          git push
