name: Frontend CI Pipeline
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: recuperer le code
        uses: actions/checkout@v4
        
      - name: se connecter a docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: builder l'image docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }} .

      - name: pousser l'image docker
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }}

      - name: Update Kubernetes Manifest
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"
          git clone https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository_owner }}/travelo_k8s.git
          cd travelo_k8s
          # Mettre Ã  jour le tag de l'image pour le frontend
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }}|" frontend_deployment.yml
          git add frontend_deployment.yml
          git commit -m "Update frontend image to ${{ github.ref_name }}"
          git push origin main

