name: Frontend CI Pipeline
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: recuperer le code
        uses: actions/checkout@v4

      - name: se connecter a docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: builder l'image docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }} .

      - name: pousser l'image docker
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/travelo_frontend:${{ github.ref_name }}
